### ISSUE TITLE
Trait issues

### ISSUE THREAD

**Issue by gmsshadow** [WIGGLES-dev/GURPSFoundrySystem#4]
Hi

Loving the game system by the way, but it seems to be doing something random at the moment. The self-control roll option seems to have switched from the disadvantages tab to the advantages tab for some reason. It was in the right place before as I used it correctly initially. Also, the traits now seem to default back to the 'no level' version even if I try and change them back again. It works for the calculation of character points but the modifiers don't pull through to skills etc.

I _think_ it happened when I imported a character from GCS, but I'm not 100% sure. I'm running on an AWS EC2 instance of Amazon Linux so I'll see if I can roll it back somehow and try again. I know if I create a new game the problem persists.

Hope that doesn't seem negative as so far yours is the best GURPS system for Foundry by miles!

Barry

**Comment by WIGGLES-dev** [comment]
Thanks for the feedback, I know there are a lot of bugs and I'm working my way through them to get the features that exist now as stable as possible. I also noticed that importing seems to not work with leveled traits and will fix that with the next release along with the error of CR showing up on advantages instead of disadvantages.

**Comment by WIGGLES-dev** [comment]
closing, fixed in 1.3
